---
deployment:
  tasks:
    - /usr/bin/echo "== BEGIN DEPLOY =="
    - /usr/bin/echo "Working dir: $(pwd)"
    - /usr/bin/ls -la .

    # Dossier cible de ton sous-domaine
    - export DEPLOYPATH=/home/keze7545/public_html/tp
    - /usr/bin/mkdir -p "$DEPLOYPATH"

    # Synchronisation des fichiers
    - /usr/bin/rsync -av --delete \
        --exclude ".git*" \
        --exclude ".github" \
        --exclude ".cpanel.yml" \
        --exclude "README.md" \
        ./ "$DEPLOYPATH"/

    - /usr/bin/echo "== FILES IN TARGET =="
    - /usr/bin/ls -la "$DEPLOYPATH"
    - /usr/bin/echo "== END DEPLOY =="
