---
deployment:
  tasks:
    - export DEPLOY_FOLDER="${DEPLOY_FOLDER:-tp}"
    - export DEPLOYPATH="$HOME/public_html/${DEPLOY_FOLDER}"
    - /bin/mkdir -p "$DEPLOYPATH"
    - /usr/bin/rsync -az --delete --exclude ".git/" --exclude ".github/" ./ "$DEPLOYPATH/"
    - /usr/bin/find "$DEPLOYPATH" -type d -exec chmod 755 {} \;
    - /usr/bin/find "$DEPLOYPATH" -type f -exec chmod 644 {} \;
