---
deployment:
  tasks:
    - export REPO_NAME="$(basename "$(pwd)")"
    - if [ "$REPO_NAME" = "release" ]; then export TARGET_DIR="$HOME/public_html/release"; else export TARGET_DIR="$HOME/public_html/tp"; fi
    - echo "📦 Repo: $REPO_NAME"
    - echo "🎯 Target: $TARGET_DIR"

    - /bin/mkdir -p "$TARGET_DIR"

    - /bin/rsync -az --delete \
        --exclude=".git/" \
        --exclude=".github/" \
        --exclude=".cpanel.yml" \
        ./ "$TARGET_DIR/"

    - /bin/find "$TARGET_DIR" -type d -exec chmod 755 {} \;
    - /bin/find "$TARGET_DIR" -type f -exec chmod 644 {} \;
    - if [ -f "$TARGET_DIR/.htaccess" ]; then chmod 644 "$TARGET_DIR/.htaccess"; fi

    - echo "✅ Deployed to $TARGET_DIR"
