---
deployment:
  tasks:
    # 1) Chemin du dossier public_html/tp sur ton hébergement
    - export DEPLOYPATH=/home/keze7545/public_html/tp

    # 2) Synchronise les fichiers du repo vers le dossier de ton site
    - /bin/rsync -az --delete \
        --exclude ".git*" \
        --exclude ".github" \
        --exclude ".cpanel.yml" \
        --exclude "README.md" \
        ./  "$DEPLOYPATH"




