deployment:
  tasks:
    - export DEPLOYPATH=/home/keze7545/public_html/tp
    - /bin/rsync -az --delete \
        --exclude ".git*" \
        --exclude ".github" \
        --exclude ".cpanel.yml" \
        --exclude "README.md" \
        ./ "$DEPLOYPATH"
