---
deployment:
  tasks:
    - set -e
    - echo "== BEGIN $(date)"
    - echo "PWD: $(pwd)"
    - echo "-- Source listing --"
    - ls -la .

    # Chemin de déploiement = document root du sous-domaine
    - export DEPLOYPATH=/home/keze7545/public_html/tp
    - mkdir -p "$DEPLOYPATH"

    # cPanel recommande d'exécuter depuis le working tree (.)
    # Utilise rsync du système (/usr/bin/rsync sur o2switch)
    - /usr/bin/rsync -av --delete \
        --exclude ".git*" \
        --exclude ".github" \
        --exclude ".cpanel.yml" \
        --exclude "README.md" \
        ./ "$DEPLOYPATH"/

    - echo "-- Target listing --"
    - ls -la "$DEPLOYPATH"
    - echo "== END $(date)"
