---
deployment:
  tasks:
    # Dossier de déploiement (par défaut: tp). Le workflow peut surcharger DEPLOY_FOLDER.
    - export DEPLOY_FOLDER="${DEPLOY_FOLDER:-tp}"
    - export DEPLOYPATH="$HOME/public_html/${DEPLOY_FOLDER}"
    - /bin/echo "Deploying to $DEPLOYPATH"

    # Crée le dossier si besoin
    - /bin/mkdir -p "$DEPLOYPATH"

    # Sync du working tree vers le docroot
    - /usr/bin/rsync -az --delete --exclude ".git/" --exclude ".github/" ./ "$DEPLOYPATH/"

    # Permissions safe (évite 403)
    - /usr/bin/find "$DEPLOYPATH" -type d -exec chmod 755 {} \;
    - /usr/bin/find "$DEPLOYPATH" -type f -exec chmod 644 {} \;

    # Trace (utile en debug)
    - /bin/echo "Deployed on $(/bin/date -Iseconds)" > "$DEPLOYPATH/deploy-info.txt"


